apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    metadata:
      annotations:
        app.kubernetes.io/vcs-ref: "0dfa101798c46671790ead5d32f86c115473127b"
        app.kubernetes.io/vcs-uri: "https://github.com/vimalkansal/gitops-demo-app"
        deploy-time: "2025-08-12T00:32:09Z"