apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-failure-data
  namespace: pelorus
  labels:
    app.kubernetes.io/name: failure-data
    app.kubernetes.io/part-of: pelorus
data:
  # Example failure data for MTTR calculation
  # In production, this would be populated by your incident management system
  failures.json: |
    [
      {
        "app": "demo-app",
        "namespace": "pelorus-demo",
        "failure_time": "2025-08-11T10:00:00Z",
        "resolution_time": "2025-08-11T10:30:00Z",
        "incident_id": "INC001",
        "severity": "high",
        "root_cause": "Database connection timeout",
        "resolved_by": "automated-rollback"
      },
      {
        "app": "demo-app",
        "namespace": "pelorus-demo",
        "failure_time": "2025-08-10T14:00:00Z",
        "resolution_time": "2025-08-10T14:15:00Z",
        "incident_id": "INC002",
        "severity": "medium",
        "root_cause": "Memory leak in application",
        "resolved_by": "manual-fix"
      }
    ]