name: build-and-update-manifests

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute short SHA
        id: vars
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}
          TAG=${{ steps.vars.outputs.sha_short }}
          docker build \
            --build-arg VCS_REF=${GITHUB_SHA} \
            --build-arg VCS_URL=https://github.com/${{ github.repository }} \
            -t $IMAGE:$TAG -t $IMAGE:latest .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

      - name: Update overlay image tag and Pelorus annotations
        run: |
          # Update image tag
          sed -i "s|newName: .*|newName: ghcr.io/${{ github.repository }}|g" k8s/overlays/prod/kustomization.yaml
          sed -i "s|newTag: .*|newTag: ${{ steps.vars.outputs.sha_short }}|g" k8s/overlays/prod/kustomization.yaml
          
          # Update all Pelorus annotations for DORA metrics
          DEPLOY_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          BUILD_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          # Create a temporary file with all replacements
          cp k8s/overlays/prod/deployment-patch.yaml k8s/overlays/prod/deployment-patch.yaml.tmp
          
          # Update all annotation placeholders
          sed -i "s|app.kubernetes.io/vcs-ref: \"WILL_BE_REPLACED_BY_CI\"|app.kubernetes.io/vcs-ref: \"${GITHUB_SHA}\"|g" k8s/overlays/prod/deployment-patch.yaml
          sed -i "s|deploy-time: \"WILL_BE_REPLACED_BY_CI\"|deploy-time: \"${DEPLOY_TIME}\"|g" k8s/overlays/prod/deployment-patch.yaml
          sed -i "s|app.kubernetes.io/build-id: \"WILL_BE_REPLACED_BY_CI\"|app.kubernetes.io/build-id: \"${{ github.run_number }}\"|g" k8s/overlays/prod/deployment-patch.yaml
          sed -i "s|app.kubernetes.io/build-url: \"WILL_BE_REPLACED_BY_CI\"|app.kubernetes.io/build-url: \"${BUILD_URL}\"|g" k8s/overlays/prod/deployment-patch.yaml
          sed -i "s|app.kubernetes.io/change-id: \"WILL_BE_REPLACED_BY_CI\"|app.kubernetes.io/change-id: \"${{ github.event.pull_request.number || github.sha }}\"|g" k8s/overlays/prod/deployment-patch.yaml
          sed -i "s|app.kubernetes.io/approved-at: \"WILL_BE_REPLACED_BY_CI\"|app.kubernetes.io/approved-at: \"${DEPLOY_TIME}\"|g" k8s/overlays/prod/deployment-patch.yaml
          
          # Commit changes
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add k8s/overlays/prod/kustomization.yaml k8s/overlays/prod/deployment-patch.yaml
          git commit -m "Update image to ${{ steps.vars.outputs.sha_short }} and Pelorus annotations" || echo "No changes to commit"
          git push




