name: build-and-update-manifests

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute short SHA
        id: vars
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}
          TAG=${{ steps.vars.outputs.sha_short }}
          docker build \
            --build-arg VCS_REF=${GITHUB_SHA} \
            --build-arg VCS_URL=https://github.com/${{ github.repository }} \
            -t $IMAGE:$TAG -t $IMAGE:latest .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

      - name: Update overlay image tag
        run: |
          sed -i "s|newName: .*|newName: ghcr.io/${{ github.repository }}|g" k8s/overlays/prod/kustomization.yaml
          sed -i "s|newTag: .*|newTag: ${{ steps.vars.outputs.sha_short }}|g" k8s/overlays/prod/kustomization.yaml
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add k8s/overlays/prod/kustomization.yaml
          git commit -m "Update image to ${{ steps.vars.outputs.sha_short }}" || echo "No changes to commit"
          git push




